name: Alpine Matrix Example

on: [workflow_dispatch]

jobs:
 build:
    name: Run ${{ github.run_id }} - ${{ github.run_number }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: ['3.14', '3.15']
    steps:
      - name: Run on Alpine container
        uses: docker://alpine:latest
        with:
          args: echo "Running on Alpine container"
