name: attempts
run-name: ${{ github.actor }} is learning GitHub Actions
on:
  workflow_dispatch:

jobs:
  pre:
    runs-on: ubuntu-latest

    steps:
      - run: date
      - run: exit 0
  post:
    runs-on: ubuntu-latest
    needs: pre
    steps:
     - run: date
     - run: exit 0

  indep:
    runs-on: ubuntu-latest
    steps:
      - run: date
      - run: exit 0
