name: attempts
on:
  workflow_dispatch:

jobs:
  pre:
    runs-on: ubuntu-latest

    steps:
      - run: exit 0
  post:
    runs-on: ubuntu-latest
    needs: pre
    steps:
     - run: exit 0

  indep:
    runs-on: ubuntu-latest
    steps:
      - run: exit 0
