name: calls
on:
  workflow_dispatch:

jobs:
  call_nested_workflow:
    uses: TheFox0x7/edge-cases/.github/workflows/middleman.yaml@main

  call_normal_workflow_but_its_matrix:
    needs: call_nested_workflow
    uses: TheFox0x7/edge-cases/.github/workflows/whatif.yaml@main
    strategy:
      matrix:
        misc: ["a","b","c"]
    with:
      misc: ${{ matrix.misc }}
  
