
on:
  workflow_dispatch:
    inputs:
        image1:
        image2:
  
jobs:
  test:
    strategy:
      matrix:
        image: ["${{ inputs.image1 }}", "${{ inputs.image2 }}"]
    name: Test
    runs-on: "${{ matrix.image }}"

    steps:
      - name: Test with inputs
        run: |
          echo "${{ toJson(strategy) 
      - name: Test with inputs
        run: |
          echo "${{ toJson(inputs) }}"
