
on:
  workflow_dispatch
  
jobs:
  test:
    strategy:
      matrix:
        image: [ubuntu]
        version: [20.04,22.04]
    name: Test
    runs-on: ["self-hosted","${{ matrix.image }}","${[ matrix.version }}"]

    steps:
      - name: Test with inputs
        run: |
          echo "${{ toJson(strategy) }}"
