
on:
  workflow_dispatch:
    inputs:
      couple:
      checks:

env: 
  key: value
  
jobs:
  test:
    name: Test
    runs-on: "ubuntu-latest"

    steps:
      - name: Test with inputs
        run: |
          echo "${{ toJson(strategy) }}"
      - name: Test with inputs
        run: |
          echo "${{ toJson(inputs) }}"
      - name: Test with 2 expressions
        run: |
          echo "${{ toJson(inputs) }}    ${{ toJson(env) }}"
