name: randoms


on:

  workflow_dispatch:
env:
  myNull: ${{ null }}
  myBoolean: ${{ false }}
  myIntegerNumber: ${{ 711 }}
  myFloatNumber: ${{ -9.2 }}
  myHexNumber: ${{ 0xff }}
  myExponentialNumber: ${{ -2.99e-2 }}
  myString: Mona the Octocat
  myStringInBraces: ${{ 'It''s open source!' }}


jobs:
  
  env_test:
    runs-on: ubuntu-latest 
    steps:
      - run: env
      - run: echo "${{ format('{{Hello {0} {1} {2}}}', 'Mona', 'the', 'Octocat') }}"

