on:
  workflow_dispatch:

jobs:
  pre:
    runs-on: ubuntu-latest
    outputs:
      what_do_i_need: ${{ steps.setup.outputs.what_do_i_need }}
    steps:
      - run: echo "what_do_i_need=ubuntu-latest" >> "$GITHUB_OUTPUT"
        id: setup

  
  env_test:
    runs-on: ${{ needs.pre.outputs.what_do_i_need }}
    needs: pre
    
    
    steps:
      - run: exit 0
