on: workflow_dispatch

jobs:
  pre:
    outputs:
      how_much: ${{ steps.setup.outputs.how_much }}

    runs-on: ubuntu-latest

    steps:
      - id: how_much
        name: Test next on node 18,20 and 22
        run: echo "how_much=[18,20,22]">> "$GITHUB_OUTPUT"

  post:
    needs: pre
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ${{ fromjson(needs.pre.outputs.how_much) }}

    steps:
      - run: exit 0
