on: 
  workflow_dispatch:
  workflow_call:
    inputs:
      misc:
        required: true
        type: string

jobs:
  pre:
    outputs:
      how_much: ${{ steps.pre.outputs.how_much }}

    runs-on: ubuntu-latest

    steps:
      - id: pre
        name: Test next on node 18,20 and 22
        run: echo "how_much=[18,20,22]">> "$GITHUB_OUTPUT"

  post:
    needs: pre
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ${{ fromjson(needs.pre.outputs.how_much) }}

    steps:
      - run: exit 0
